# See https://zmk.dev/docs/config for more details.

# The name of the keyboard (max 16 characters).
CONFIG_ZMK_KEYBOARD_NAME="Sofle Choc Pro"

# Enable deep sleep support.
CONFIG_ZMK_SLEEP=y

# Milliseconds of inactivity before entering idle state.
CONFIG_ZMK_IDLE_TIMEOUT=60000

# Milliseconds of inactivity before entering deep sleep.
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
