manifest:
  remotes:
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: keebart
      url-base: https://github.com/Keebart

  projects:
    - name: zmk-keebart
      revision: main
      remote: keebart
      repo-path: zmk-config
      import: config/west.yml
  self:
    path: config
